# ===================================================================
# ?????????FDFS????
# ===================================================================
fdfs:
  soTimeout: 1500 #socket?????????
  connectTimeout: 600 #????tracker????????????
  resHost: 192.168.166.183
  storagePort: 8080
  thumbImage: #?????????????????
    width: 150
    height: 150
  trackerList: #TrackerList????,?????????????????????????§Ø?????¡¤???- x.x.x.x:port
    - 192.168.166.181:22122
